name: clang-tidy-review

on:
  pull_request:
    branches:
      - master

jobs:
  Clang-Tidy:
    runs-on: ${{ vars.USE_SELF_HOSTED == 'true' && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: ClangTidy Gen
        uses: sombraSoft/clang-tidy-review@clang-tidy-dep-fix
        id: review
        with:
          build_dir: "./build"
          cmake_command: >-
            which cmake &&
            cmake --version &&
            ls -l /usr/lib/x86_64-linux-gnu/cmake/yaml-cpp &&
            dpkg -L libyaml-cpp-dev &&
            cmake . -B build
          config_file: ".clang-tidy"
          exclude: "*/codeGenerator/templates/*,*/third-party/*"
          split_workflow: true
          apt_packages: libomp-15-dev,libfl-dev
      - uses: sombraSoft/clang-tidy-review/upload@clang-tidy-dep-fix
        id: upload-review
      - name: Correct Build Directory Ownership
        if: always()
        run: |
          echo "Attempting to change ownership of ${{ github.workspace }} back to runner user..."
          sudo /usr/bin/chown -R $(id -u):$(id -g) ${{ github.workspace }}
          echo "Ownership change attempt finished."
        shell: bash
      - if: steps.review.outputs.total_comments > 0
        run: |
          echo "Pending review comments. Please resolve all comments before merging."
          exit 1
